manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kzk-split-shield
      url-base: git@github.com-jrkozak92:jrkozak92
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: kzk_split_shield
      remote: kzk-split-shield
      import: true
      revision: main
  self:
    path: config
